return {}
--
-- TODO: Copilot can't auth until xdg is set correctly
-- return {
--   kokovim.get_plugin("copilot.lua", "zbirenbaum/copilot.lua", {
--     cmd = "Copilot",
--     build = ":Copilot auth",
--     event = "BufReadPost",
--     opts = {
--       suggestion = {
--         enabled = true,
--         auto_trigger = true,
--         hide_during_completion = true,
--         keymap = {
--           accept = false, -- handled by nvim-cmp / blink.cmp
--           next = "<M-]>",
--           prev = "<M-[>",
--         },
--       },
--       panel = { enabled = false },
--       filetypes = {
--         markdown = true,
--         help = true,
--       },
--     },
--     config = function(_, opts) require("copilot").setup(opts) end,
--     -- TODO: Authentication is failing for now, can't write to the folder
--   }),
--   -- kokovim.get_plugin("CopilotChat.nvim", "CopilotC-Nvim/CopilotChat.nvim", {
--   --   dependencies = {
--   --     kokovim.get_plugin("copilot.lua", "zbirenbaum/copilot.lua"),
--   --     kokovim.get_plugin("plenary.nvim", "nvim-lua/plenary.nvim"),
--   --   },
--   --   build = "make tiktoken",
--   --   opts = {
--   --     -- See Configuration section for options
--   --   },
--   -- }),
--   kokovim.get_plugin("codecompanion.nvim", "olimorris/codecompanion.nvim", {
--     dependencies = {
--       kokovim.get_plugin("plenary.nvim", "nvim-lua/plenary.nvim"),
--       kokovim.get_plugin("nvim-treesitter", "nvim-treesitter/nvim-treesitter"),
--     },
--     opts = {
--       language = "English",
--       opts = {
--         -- Set debug logging
--         log_level = "DEBUG",
--       },
--     },
--   }),
-- }
