-- local utils = require("kokovim.utils")
-- local roslyn_path = utils.get_package_path("roslyn")
-- local rzls_path = utils.get_package_path("rzls")
--
-- local roslyn_nix = kokovim.is_nix
--     and {
--       exe = vim.fs.joinpath(roslyn_path, "bin", "Microsoft.CodeAnalysis.LanguageServer"),
--       args = {
--         "--razorSourceGenerator="
--           .. vim.fs.joinpath(roslyn_path, "lib", "roslyn-ls", "Microsoft.CodeAnalysis.Razor.Compiler.dll"),
--         "--razorDesignTimePath="
--           .. vim.fs.joinpath(rzls_path, "lib", "rzls", "Targets", "Microsoft.NET.Sdk.Razor.DesignTime.targets"),
--       },
--     }
--   or {}
--
-- return {
--   kokovim.get_plugin_by_repo("seblyng/roslyn.nvim", {
--     ft = "cs",
--     ---@module 'roslyn.config'
--     ---@type RoslynNvimConfig
--     opts = {
--       args = {
--         "--stdio",
--         "--logLevel=Information",
--         "--extensionLogDirectory=" .. vim.fs.dirname(vim.lsp.get_log_path()),
--       },
--       config = {
--         handlers = require("rzls.roslyn_handlers"),
--         settings = {
--           ["csharp|completion"] = {
--             dotnet_provide_regex_completions = true,
--             dotnet_show_completion_items_from_unimported_namespaces = true,
--             dotnet_show_name_completion_suggestions = true,
--           },
--           ["csharp|formatting"] = {
--             dotnet_organize_imports_on_format = true,
--           },
--           ["csharp|symbol_search"] = {
--             dotnet_search_reference_assemblies = true,
--           },
--
--           ["csharp|inlay_hints"] = {
--             csharp_enable_inlay_hints_for_implicit_object_creation = true,
--             csharp_enable_inlay_hints_for_implicit_variable_types = true,
--
--             csharp_enable_inlay_hints_for_lambda_parameter_types = true,
--             csharp_enable_inlay_hints_for_types = true,
--             dotnet_enable_inlay_hints_for_indexer_parameters = true,
--             dotnet_enable_inlay_hints_for_literal_parameters = true,
--             dotnet_enable_inlay_hints_for_object_creation_parameters = true,
--             dotnet_enable_inlay_hints_for_other_parameters = true,
--             dotnet_enable_inlay_hints_for_parameters = true,
--             dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix = true,
--             dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name = true,
--             dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent = true,
--           },
--           ["csharp|code_lens"] = {
--             dotnet_enable_references_code_lens = true,
--             dotnet_enable_tests_code_lens = true,
--           },
--         },
--       },
--     },
--     config = function(_, opts)
--       vim.tbl_deep_extend("force", opts, roslyn_nix)
--       require("roslyn").setup(opts)
--     end,
--   }),
-- }
--
return {

}
